import { Card } from "../src/Card"
import { EffectType } from "../src/effects"
import { v4 as uuid } from "uuid"

export const cards: Card[] = [
	{ id: uuid(), tags: ["A", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["1", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["2", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["3", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["4", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["5", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["6", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["7", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["8", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["9", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["10", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["J", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["Q", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["K", "Clubs"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["A", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["1", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["2", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["3", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["4", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["5", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["6", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["7", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["8", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["9", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["10", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["J", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["Q", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["K", "Diamonds"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["A", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["1", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["2", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["3", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["4", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["5", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["6", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["7", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["8", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["9", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["10", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["J", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["Q", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["K", "Hearts"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["A", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["1", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["2", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["3", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["4", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["5", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["6", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["7", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["8", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["9", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["10", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["J", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["Q", "Spades"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["K", "Spades"], playableOnTags: [], effects: [], options: {} },
]

export const jokers = [
	{ id: uuid(), tags: ["Joker", "Black"], playableOnTags: [], effects: [], options: {} },
	{ id: uuid(), tags: ["Joker", "Red"], playableOnTags: [], effects: [], options: {} },
]

export const withJokers = [...cards, ...jokers]
