import { Card } from "../src/Card"

export const cards: Card[] = [
	{ tags: ["A", "Clubs"], effects: [], options: [] },
	{ tags: ["1", "Clubs"], effects: [], options: [] },
	{ tags: ["2", "Clubs"], effects: [], options: [] },
	{ tags: ["3", "Clubs"], effects: [], options: [] },
	{ tags: ["4", "Clubs"], effects: [], options: [] },
	{ tags: ["5", "Clubs"], effects: [], options: [] },
	{ tags: ["6", "Clubs"], effects: [], options: [] },
	{ tags: ["7", "Clubs"], effects: [], options: [] },
	{ tags: ["8", "Clubs"], effects: [], options: [] },
	{ tags: ["9", "Clubs"], effects: [], options: [] },
	{ tags: ["10", "Clubs"], effects: [], options: [] },
	{ tags: ["J", "Clubs"], effects: [], options: [] },
	{ tags: ["Q", "Clubs"], effects: [], options: [] },
	{ tags: ["K", "Clubs"], effects: [], options: [] },
	{ tags: ["A", "Diamonds"], effects: [], options: [] },
	{ tags: ["1", "Diamonds"], effects: [], options: [] },
	{ tags: ["2", "Diamonds"], effects: [], options: [] },
	{ tags: ["3", "Diamonds"], effects: [], options: [] },
	{ tags: ["4", "Diamonds"], effects: [], options: [] },
	{ tags: ["5", "Diamonds"], effects: [], options: [] },
	{ tags: ["6", "Diamonds"], effects: [], options: [] },
	{ tags: ["7", "Diamonds"], effects: [], options: [] },
	{ tags: ["8", "Diamonds"], effects: [], options: [] },
	{ tags: ["9", "Diamonds"], effects: [], options: [] },
	{ tags: ["10", "Diamonds"], effects: [], options: [] },
	{ tags: ["J", "Diamonds"], effects: [], options: [] },
	{ tags: ["Q", "Diamonds"], effects: [], options: [] },
	{ tags: ["K", "Diamonds"], effects: [], options: [] },
	{ tags: ["A", "Hearts"], effects: [], options: [] },
	{ tags: ["1", "Hearts"], effects: [], options: [] },
	{ tags: ["2", "Hearts"], effects: [], options: [] },
	{ tags: ["3", "Hearts"], effects: [], options: [] },
	{ tags: ["4", "Hearts"], effects: [], options: [] },
	{ tags: ["5", "Hearts"], effects: [], options: [] },
	{ tags: ["6", "Hearts"], effects: [], options: [] },
	{ tags: ["7", "Hearts"], effects: [], options: [] },
	{ tags: ["8", "Hearts"], effects: [], options: [] },
	{ tags: ["9", "Hearts"], effects: [], options: [] },
	{ tags: ["10", "Hearts"], effects: [], options: [] },
	{ tags: ["J", "Hearts"], effects: [], options: [] },
	{ tags: ["Q", "Hearts"], effects: [], options: [] },
	{ tags: ["K", "Hearts"], effects: [], options: [] },
	{ tags: ["A", "Spades"], effects: [], options: [] },
	{ tags: ["1", "Spades"], effects: [], options: [] },
	{ tags: ["2", "Spades"], effects: [], options: [] },
	{ tags: ["3", "Spades"], effects: [], options: [] },
	{ tags: ["4", "Spades"], effects: [], options: [] },
	{ tags: ["5", "Spades"], effects: [], options: [] },
	{ tags: ["6", "Spades"], effects: [], options: [] },
	{ tags: ["7", "Spades"], effects: [], options: [] },
	{ tags: ["8", "Spades"], effects: [], options: [] },
	{ tags: ["9", "Spades"], effects: [], options: [] },
	{ tags: ["10", "Spades"], effects: [], options: [] },
	{ tags: ["J", "Spades"], effects: [], options: [] },
	{ tags: ["Q", "Spades"], effects: [], options: [] },
	{ tags: ["K", "Spades"], effects: [], options: [] },
]

export const jokers = [
	{ tags: ["Joker"], effects: [], options: [] },
	{ tags: ["Joker"], effects: [], options: [] },
]

export const withJokers = [...cards, ...jokers]
